### ISSUE TITLE
Feature Request: Option to read a value from inside the secret for key/value secerts

### ISSUE THREAD

**Issue by marcelobartsch** [aws/secrets-store-csi-driver-provider-aws#11]
When a secret has a JSON document , for example on the case of key/value secret, would be nice to be able to select the key you want on a particular secret, for Opaque secrets for example

looking at the vault provider they do something like this here
https://github.com/hashicorp/vault-csi-provider/blob/master/internal/provider/provider.go#L151

for example , if we have the secret `arn:aws:secretsmanager:us-east-9:000000000000:secret:secret/key-value-secret`

which contains
key1 = value1
key2 = value2

currently if we use that, we get a JSON document (either in filesystem or environment variable)

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: chips
spec:
  provider: aws
  secretObjects:
  - secretName: aws-csi-test
    type: Opaque
    labels:
      environment: pro
    data:
    - objectName: values
      key: "vals"
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:us-east-9:000000000000:secret:secret/key-value-secret"
          objectAlias: values
          objectType: "secretsmanager"
```

and would be nice to be able to have something where we can , either, access the key directly or somehow autopopulate the Opaque secret with key=value data

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: chips
spec:
  provider: aws
  secretObjects:
  - secretName: aws-csi-test
    type: Opaque
    labels:
      environment: pro
    data:
    - objectName: values["key1"]
      key: "key1"
    - objectName: values.["key2"}
      key: "key1"
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:us-east-9:000000000000:secret:secret/key-value-secret"
          objectAlias: values
          objectType: "secretsmanager"
```

**Comment by joebaro** [comment]
Thank you for your feedback. Please note that the AWS provider is a plugin to the [Secrets Store CSI driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver) and as such provides secrets to the driver. The driver itself is responsible for getting these secrets into K8s secrets and variables. Any feature like this would have to extract a single value and store that as the mounted secret and pass only that extracted value to the driver.

We have noted this as a feature request.

**Comment by david74chou** [comment]
I think this would be a very useful feature that we could extract individual key/value from SSM parameter or SecretManager and sync the k8s secret dynamically.

example from vault: https://www.vaultproject.io/docs/platform/k8s/csi/examples#environment-variable-dynamic-database-credentials.

Without this feature, I can't figure out how to workaround if we want to put all key/value pairs under one single SSM parameter or SecretManager secret then ingest into environment variable separately via `secretKeyRef` or `envFrom`.

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-db-creds
spec:
  provider: vault
  secretObjects:
  - secretName: vault-db-creds-secret
    type: Opaque
    data:
    - objectName: dbUsername # References dbUsername below
      key: username          # Key within k8s secret for this value
    - objectName: dbPassword
      key: password
  parameters:
    roleName: "app"
    vaultAddress: "https://vault.vault:8200"
    vaultCACertPath: "/vault/tls/ca.crt"
    objects: |
      - objectName: "dbUsername"
        secretPath: "database/creds/db-app"
        secretKey: "username"
      - objectName: "dbPassword"
        secretPath: "database/creds/db-app"
        secretKey: "password"
```
