### ISSUE TITLE
How do I mount multiple secrets to distinct paths?

### ISSUE THREAD

**Issue by jesseduffield** [aws/secrets-store-csi-driver-provider-aws#134]
This is a usage question. If I have secret A that I want to mount to /app/foo/foo-A and secret B that I want to mount to /app/bar/foo-B, how could I go about that?

I've seen examples of including multiple secrets in a single SecretProviderClass but those same examples mount the secrets under the one directory, and seem to use the secret name in the resultant path. I want to not only allow for mounting two secrets in different directories but I want complete control over the mount path (meaning I don't care what the name of the secret is, I want to decide the exact path it's given in the container).

Should I be using one SecretProviderClass per secret, and is there an example anywhere that shows how I would go about this? Thanks :)

**Comment by GregCKrause** [comment]
You can do that. You can create multiple secret provider classes, volumes, and mounts.

```yml
volumes:
- name: secrets-store-inline-secret1
  csi:
    driver: secrets-store.csi.k8s.io
    readOnly: true
    volumeAttributes:
      secretProviderClass: "aws-secrets-secret1"
- name: secrets-store-inline-secret2
  csi:
    driver: secrets-store.csi.k8s.io
    readOnly: true
    volumeAttributes:
      secretProviderClass: "aws-secrets-secret2"

volumeMounts:
- name: secrets-store-inline-secret1
  mountPath: "/mnt/secrets-store-secret1"
  readOnly: true
- name: secrets-store-inline-secret2
  mountPath: "/mnt/secrets-store-secret2"
  readOnly: true
```
