### ISSUE TITLE
Cannot mount secrets to use as ImagePullSecrets

### ISSUE THREAD

**Issue by miki79** [aws/secrets-store-csi-driver-provider-aws#16]
If I define the secret as "kubernetes.io/dockerconfigjson" the secret is not created in kubernets and it cannot be used as imagePullSecrets

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets-env
spec:
  provider: aws
  secretObjects:
    - secretName: secretdocker
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: "docker_config"
          key: .dockerconfigjson
  parameters:
    objects: |
      - objectName: "/secret/docker_config"
        objectType: "ssmparameter"
        objectAlias: "docker_config"
``` 

and Pod definition
```yaml
kind: Pod
apiVersion: v1
metadata:
  name: env-example
spec:
  serviceAccountName: sa-k8s-secret-poc
  imagePullSecrets:
    - name: secretdocker
  containers:
    - image: miki79/testimage:1
      name: testimage
      imagePullPolicy: Always
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "aws-secrets-env"
```

I get the error `Warning  FailedToCreateSecret  3s (x10 over 5s)  csi-secrets-store-controller  timed out waiting for the condition`

If I modify the secretObjects type to "Opaque" the secret is created correctly.

I'm not sure if I'm doing something wrong, or `kubernetes.io/dockerconfigjson` is not supported, as I can't find any information in the documentation.

**Comment by lasred** [comment]
Thank you for opening this issue - we are looking into it.

**Comment by yossicohn-hs** [comment]
Have a similar issue.
The Secrets are mounted to `/mnt/secrets-store`as expected,  but the secret (no matter of the type) that should have been created is not created

**Comment by asonnleitner** [comment]
same

**Comment by brucedvgw** [comment]
Facing the same issue. I thought I had incorrect configuration https://github.com/aws/secrets-store-csi-driver-provider-aws/issues/38

**Comment by JRemitz** [comment]
Any updates on this @lasred? According to the [secrets store CSI driver docs](https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret.html), the type `kubernetes.io/dockerconfigjson` is supported.

**Comment by JRemitz** [comment]
Okay... NM, I think it is working now. @miki79 - not sure if you've since given up on this but the docs I linked above might have been outdated last year? I noticed that earlier this year I upgraded to `v0.3.0` and there are newer versions.

1. I upgraded my Secrets Store CSI Driver to `v1.0.1` (note, they _just_ released `v1.1.0` but I'm not  on that yet). I don't see a release in the chart yet.
1. I upgraded my secret to `apiVersion: secrets-store.csi.x-k8s.io/v1`
1. After updating my pod I'm able to connect. I see the docker secret created and no events logged for an invalid ImagePullSecret.


More info for anyone else trying from scratch:
1. AWS SSM - SecureString - contains JSON format of the docker-registry secret
1. I have a ServiceAccount annotated with the correct role to the SSM secure string AND KMS key to decrypt the value (if needed)
1. My secret looks like the example in the issue, copied here for reference:
    ```yaml
    ---
    apiVersion: secrets-store.csi.x-k8s.io/v1
    kind: SecretProviderClass
    metadata:
      name: docker-hub
    spec:
      provider: aws
      secretObjects:
        - secretName: docker-hub
          type: kubernetes.io/dockerconfigjson
          data:
            - objectName: "docker-configjson"
              key: ".dockerconfigjson"
      parameters:
        region: us-east-1
        objects: |
          - objectName: "/secret/docker_config"
            objectAlias: docker-configjson
            objectType: "ssmparameter"
    ```
1. Volume and Mounts like so:
    ```yaml
    volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "docker-hub"
    
    volumeMounts:
      - name: secrets-store-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
    ```
1. ServiceAccount attached to pod
1. ImagePullSecrets added for secret reference:
    ```yaml
    imagePullSecrets:
      - name: "docker-hub"
    ```
