### ISSUE TITLE
AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity

### ISSUE THREAD

**Issue by vito-laurenza-zocdoc** [aws/secrets-store-csi-driver-provider-aws#17]
I have the csi driver and aws provider installed on my eks cluster. I am attempting to follow the instructions for usage, but my test pod is getting the following error trying to mount the secret:

```
  Warning  FailedMount  41m  kubelet  MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/nginx-deployment-74d68b559b-lsfr9, err: rpc error: code = Unknown desc = Failed fetching parameters: WebIdentityErr: failed to retrieve credentials
caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity
           status code: 403, request id: 74069505-0a96-4068-a6ea-4e37e1bf9f9d
```

Here is the corresponding event from Cloud Trail:
```json
{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "WebIdentityUser",
        "principalId": "arn:aws:iam::000000000000:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/00000000000000000000000000000000:sts.amazonaws.com:system:serviceaccount:default:vitotest-sa",
        "userName": "system:serviceaccount:default:vitotest-sa",
        "identityProvider": "arn:aws:iam::000000000000:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/00000000000000000000000000000000"
    },
    "eventTime": "2021-05-24T20:16:19Z",
    "eventSource": "sts.amazonaws.com",
    "eventName": "AssumeRoleWithWebIdentity",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "x.x.x.x",
    "userAgent": "aws-sdk-go/1.37.0 (go1.15.8; linux; amd64)",
    "errorCode": "AccessDenied",
    "errorMessage": "An unknown error occurred",
    "requestParameters": {
        "roleArn": "arn:aws:iam::000000000000:role/eksctl-my-cluster-name-addon-iamserviceaccou-Role1-000000000000",
        "roleSessionName": "secrets-store-csi-driver-provider-aws"
    },
    "responseElements": null,
    "requestID": "74069505-0a96-4068-a6ea-4e37e1bf9f9d",
    "eventID": "e3f6f433-c6e5-45fa-a970-f629aca1d037",
    "readOnly": true,
    "resources": [
        {
            "accountId": "000000000000",
            "type": "AWS::IAM::Role",
            "ARN": "arn:aws:iam::000000000000:role/eksctl-my-cluster-name-addon-iamserviceaccou-Role1-000000000000"
        }
    ],
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "eventCategory": "Management",
    "recipientAccountId": "000000000000",
    "tlsDetails": {
        "tlsVersion": "TLSv1.2",
        "cipherSuite": "ECDHE-RSA-AES128-SHA",
        "clientProvidedHostHeader": "sts.us-east-1.amazonaws.com"
    }
}
```

Steps I've taken:

1.  Associated the oidc provider with my cluster via eksctl:
```
eksctl utils associate-iam-oidc-provider --cluster my-cluster-name --region="us-east-1" --approve
```
2. Created an IAM policy with SSM permissions.
```
POLICY_ARN=$(
    aws --region us-east-1 --query Policy.Arn --output text iam create-policy \
        --policy-name vitotest-policy \
        --policy-document '{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": ["ssm:DescribeParameters", "ssm:GetParameters"],
            "Resource": ["arn:aws:ssm:us-east-1:xxx:parameter/vitotest/*"]
        },
        {
            "Effect": "Allow",
            "Action": [
              "kms:Describe*",
              "kms:List*",
              "kms:Encrypt",
              "kms:Decrypt",
              "kms:ReEncrypt*",
              "kms:GenerateDataKey*"
            ]
            "Resource": ["arn:aws:kms:us-east-1:xxx:key/xxx"]
        }
    ]}'
)
```
3. Created IAM service account via eksctl:
```
eksctl create iamserviceaccount \
    --name vitotest-sa \
    --region="us-east-1" \
    --cluster "my-cluster-name" \
    --attach-policy-arn "$POLICY_ARN" \
    --approve \
    --override-existing-serviceaccounts
```
3. Applied the following manifest to my k8s cluster:
```yaml
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vitotest-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "vitotest/mykey"
        objectType: "ssmparameter"
      - objectName: "vitotest/mysecret"
        objectType: "ssmparameter"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    owner: vito
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        owner: vito
    spec:
      serviceAccountName: vitotest-sa
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "vitotest-aws-secrets"
      containers:
      - name: nginx-deployment
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
```

**Comment by vito-laurenza-zocdoc** [comment]
We found the root cause of the issue, which was two-fold.

1. We hit [this scenario](https://github.com/weaveworks/eksctl/issues/3645#issuecomment-847939633) with `eksctl`, which was confusing at best.
2. The `objectName`s in my `SecretProviderClass` resource were missing the leading slash for ssm param names. (I thought I read that the leading slash should be left off, but I can't find where I saw that now). The correct format should be:
```yaml
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vitotest-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "/vitotest/mykey"
        objectType: "ssmparameter"
      - objectName: "/vitotest/mysecret"
        objectType: "ssmparameter"
```
