### ISSUE TITLE
Querying for JSON formatted secrets using jmesPath does not work

### ISSUE THREAD

**Issue by elin902** [aws/secrets-store-csi-driver-provider-aws#217]
**Describe the bug**
I'm trying to retrieve secrets from a JSON formatted secret in the AWS secrets manager and create kubernetes secrets using the SecretProviderClass. 

The secret in AWS SM named "secret":
`{"SECRET_KEY":"testkey"}`

SecretProviderClass:
```
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: test-secrets
spec:
  provider: aws
  secretObjects:
    - secretName: secrets
      type: Opaque
      data:
        - objectName: secret-key
          key: SECRET_KEY
  parameters:
    objects: |
      - objectName: "secrets"
        objectType: "secretsmanager"
        jmesPath:
          - path: "SECRET_KEY"
            objectAlias: "secret-key"
```
Deployment:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-secrets
  namespace: test-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-secrets
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-secrets
    spec:
      serviceAccountName: secrets-sa
      volumes:
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: aws-secrets
      containers:
        - name: test-secrets
          image: test-secrets:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
              protocol: TCP
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SECRET_KEY
          volumeMounts:
            - name: secrets
              mountPath: /mnt/secret-key
              readOnly: true
```
The errors from the POD's description:
```
  Warning  Failed                13s (x3 over 25s)  kubelet                       Error: secret "secrets" not found
  Warning  FailedToCreateSecret  6s (x13 over 26s)  csi-secrets-store-controller  failed to get data in spc test-secrets/aws-secrets for secret secrets, err: file matching objectName secret-key not found in the pod
```
When I change the `objects` block in the scp like shown below, the secret gets created and can get consumed, although in the form of JSON which I do not want.
```
    objects: |
      - objectName: "secrets"
        objectType: "secretsmanager"
        objectAlias: "secret-key"
```
**To Reproduce**

Deploy resources as shown above

**Expected behavior**

I expect the CSI to create a secret that contains the value of the "SECRET_KEY" key in the Secrets Manager secret

**Environment:**
EKS 1.25
