### ISSUE TITLE
How can I set mounted secret permissions?

### ISSUE THREAD

**Issue by ok512** [aws/secrets-store-csi-driver-provider-aws#222]
Guys,
Need a little help here: How can I set mounted secret permission?

With **EKS secret** it's set via 
```
   secret:
     defaultMode: 0600
```
with result:
`-rw-------    1 root     root          1864 May  2 22:01 .mylogin.cnf`
With **AWS secret** it's:
`-rw-r--r--    1 root     root          1864 May  2 22:18 .mylogin.cnf`
What parameter controls it?
How do I set it to be `-rw-------`

The pod yaml is:
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  serviceAccountName: tester
  containers:
  - name: busybox
    image: registry.k8s.io/busybox:latest
    command: ["sh"]
    args:
    - -c
    - ls -la /root/
    volumeMounts:
    - name: mylogin
      mountPath: /root/.mylogin.cnf
      subPath: .mylogin.cnf
      readOnly: true
  restartPolicy: Never
  volumes:
  - name: mylogin
    csi:
      driver: secrets-store.csi.k8s.io
      defaultMode: 0600
      readOnly: true
      volumeAttributes:
        secretProviderClass: "aws.mylogin.cnf"
  # volumes:
  # - name: mylogin
  #   secret:
  #     defaultMode: 0600
  #     secretName: mysql
  #     items:
  #     - key: .mylogin.cnf
  #       path: .mylogin.cnf
```
