### ISSUE TITLE
Doesn't allow keys with hyphen "-"

### ISSUE THREAD

**Issue by vajeen** [aws/secrets-store-csi-driver-provider-aws#228]
**Describe the bug**
Secrets with  keys that has hyphens "-" are not accepted.

And the error is very misleading. I got it working after removing the hyphens from the keys.
```
MountVolume.SetUp failed for volume "credentials" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/mypod-7d8f7f9d6d-xrfwb, err: rpc error: code = Unknown desc = Failed to fetch secret from all regions: credentials

**To Reproduce**

Steps to reproduce the behavior:

```

Create a secret in AWS SecretManager that has a hyphen in the key

credentials { user-name: myusername }

And create a secretproviderclass and mount it to a pod
```
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: credentials
spec:
  provider: aws
  secretObjects:
    - secretName: username
      type: Opaque
      data:
        - objectName: username
          key: username
  parameters:
    objects: |
      - objectName: credentials
        objectType: secretsmanager
        jmesPath:
          - path: user-name
            objectAlias: username

```
Do you also notice this bug when using a different secrets store provider (Vault/Azure/GCP...)? **No**

If yes, the issue is likely with the k8s Secrets Store CSI driver, not the AWS provider. Open an issue in [that repo](https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues).

**Expected behavior**
Secret mounted successfully
