### ISSUE TITLE
Cannot specify secretObjects of SecretProviderClass that reference ASM values of integer type

### ISSUE THREAD

**Issue by jfmeachum** [aws/secrets-store-csi-driver-provider-aws#250]
**Describe the bug**
A `SecretProviderClass` specifying a `secretObject` that references an integer value stored in an ASM Secret fails to create a K8s Secret.

**To Reproduce**

Given an ASM Secret `will-fail` with the following structure:
```json
{
    "fails": 123
}
```
And a `SecretProviderClass` resource declaration:
```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: does-not-work
  namespace: example
spec:
  parameters:
    objects: |-
      - objectName: will-fail
        objectType: secretsmanager
        jmesPath:
        - path: fails
          objectAlias: fails
  provider: aws
  secretObjects:
  - data:
    - key: fails
      objectName: fails
    secretName: will-fail
    type: Opaque
```

Workloads that depend on the above will fail with the following error:
```console
Failure getting secret values from provider type secretsmanager: Failed to fetch secret from all regions: will-fail
```

**Expected behavior**

Workload containers start and are able to consume the K8s Secret as well as access the CSI driver-managed volume data.
