### ISSUE TITLE
Cannot specify jmesPath with hyphens

### ISSUE THREAD

**Issue by jfmeachum** [aws/secrets-store-csi-driver-provider-aws#251]
**Describe the bug**

A `SecretProviderClass` with a `jmesPath` that has a hyphen will fail to create a K8s Secret.

**To Reproduce**

Given an ASM Secret `will-fail` with the following structure:

```json
{
    "hyphen-fail": 123
}
```

And a `SecretProviderClass` resource declaration:

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: does-not-work
  namespace: example
spec:
  parameters:
    objects: |-
      - objectName: will-fail
        objectType: secretsmanager
        jmesPath:
        - path: hyphen-fail
          objectAlias: fails
  provider: aws
  secretObjects:
  - data:
    - key: fails
      objectName: fails
    secretName: will-fail
    type: Opaque
```

Workloads that depend on the above will fail with the following error:

```console
Failure getting secret values from provider type secretsmanager: Failed to fetch secret from all regions: will-fail
```

The provider will succeed if the explicit reference to the hyphenated key is removed.

**Expected behavior**

Workload containers start and are able to consume the K8s Secret as well as access the CSI driver-managed volume data.
