### ISSUE TITLE
Link for the Chart to download as dependency in Helm / ArgoCD

### ISSUE THREAD

**Issue by SimonOsipov** [aws/secrets-store-csi-driver-provider-aws#285]
**Describe the bug**
Hi there! I want to use `secrets-store-csi-driver-provider-aws` with ArgoCD and in order to create an application with the helm as a dependency, I need to provide a path to Chart. Currently, it is not available.

**To Reproduce**

Consider this `Chart.yaml`
<img width="329" alt="CleanShot 2023-10-17 at 19 19 53@2x" src="https://github.com/aws/secrets-store-csi-driver-provider-aws/assets/28685772/8414f92f-11a7-4a43-9752-f2776584b25e">
If I run `helm dependency update` command, it will download an archive of current charts and create a Chart.lock file.

But I can't run the same command for this `Chart.yaml`:
<img width="505" alt="CleanShot 2023-10-17 at 19 21 50@2x" src="https://github.com/aws/secrets-store-csi-driver-provider-aws/assets/28685772/bed03ca3-e768-4e02-9607-935194d6ff79">

I am getting the error: `Error: secrets-store-csi-provider-aws chart not found in repo https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts`.
This link provided in the documentation lead to webpage, not to the chart:
<img width="687" alt="CleanShot 2023-10-17 at 19 22 38@2x" src="https://github.com/aws/secrets-store-csi-driver-provider-aws/assets/28685772/e9b9590b-a606-41b8-be29-28f5aa83ab2e">

Do you also notice this bug when using a different secrets store provider (Vault/Azure/GCP...)? 
**No**

**Expected behavior**
`Chart.lock` and archive of charts downloaded.

**Environment:**
N/A

**Additional context**
N/A

**Comment by vettom** [comment]
Have you tried following? I am installing with ArgoCD and it is working. 
`
    repoURL: https://aws.github.io/secrets-store-csi-driver-provider-aws
    chart: secrets-store-csi-driver-provider-aws
    targetRevision: 0.3.4
`

**Comment by SimonOsipov** [comment]
Yes, my bad
```yaml
apiVersion: v1
name: secrets-store-csi-provider-aws
version: 1.3.4
dependencies:
  - name: secrets-store-csi-provider-aws
    version: 0.3.4
    repository: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
```
