### ISSUE TITLE
Unable to create a valid json representation of the SecretProviderClass object array

### ISSUE THREAD

**Issue by gbarker** [aws/secrets-store-csi-driver-provider-aws#37]
The readme notes that the object parameter is "most easily written using a YAML multi-line string or pipe character". Unfortunately cdk-eks will only accept json (https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-eks.KubernetesManifestProps.html).

I have tried a dozen ways to produce an acceptable json representation but can't seem to get it to work. Could you provide an example that would produce the equivalent of?:

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: my-secrets
  namespace: my-namespace
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:blahblah"
        objectType: "secretsmanager"
```

Many thanks!
