### ISSUE TITLE
Error with affinity

### ISSUE THREAD

**Issue by zavertiaev** [aws/secrets-store-csi-driver-provider-aws#373]
I have a simple deployment, and I need to mount secrets from AWS SM. The deployment has tolerations and affinity. When attempting to retrieve the secrets, I receive the following error: `MountVolume.SetUp failed for volume "secrets" : rpc error: code = DeadlineExceeded desc = context deadline exceeded`.

secrets-store-csi-driver-provider-aws pod logs:
```
I0628 09:56:14.620420       1 server.go:124] Servicing mount request for pod dev-test-77b9f4876d-qv26c in namespace dev using service account dev-secretmanager-sa with region(s) eu-west-1
I0628 09:56:14.624478       1 auth.go:123] Role ARN for dev:dev-secretmanager-sa is arn:aws:iam:::role/dev-secretmanager-role
W0628 09:58:14.595198       1 secrets_manager_provider.go:84] eu-west-1: Failed fetching secret dev/secret: RequestCanceled: request context canceled
caused by: context canceled
E0628 09:58:14.595275       1 server.go:151] Failure getting secret values from provider type secretsmanager: Failed to fetch secret from all regions: dev/secret
```
`secrets-store-csi-driver` and `secrets-store-csi-driver-provider-aws` are installed via Helm with default values and necessary tolerations. The pods of both daemonsets are running on the required node.
When I run the deployment without affinity (the pods are deployed on a different node accordingly), it mounts correctly (which gives me reason to believe that service account, arn and other settings are configured correctly).

```
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: test
  namespace: dev
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "dev/secret"
          objectType: "secretsmanager"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-test
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dev-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dev-test
    spec:
      serviceAccountName: dev-secretmanager-sa
      containers:
        - name: test
          image: "alpine"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: secrets
              mountPath: "/etc/secrets"
              readOnly: true
      volumes:
        - name: secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "test"
      tolerations:
        - key: node-role/test
          operator: Equal
          value: 'true'
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: test
                    operator: In
                    values:
                      - "true"
```

It seems that this bug has already been noticed #299 
Any ideas please
