### ISSUE TITLE
Unable to retrieve Env set at the SecretProviderClass

### ISSUE THREAD

**Issue by brucedvgw** [aws/secrets-store-csi-driver-provider-aws#38]
Hi I am able to create the SecretProviderClass and pull down a secret to the mounted volume, however every time I try to create the value as a Environment variable it fails.

I have been over and over the configuration and I can not spot what I am doing wrong. Is anyone able to help 🙏🏻 

Here is my secret-provider config.

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secret-application
spec:
  provider: aws
  secretObjects:
    - secretName: database-creds-csi 
      type: Opaque
      data:
      - objectName: database-creds
        key: password
  parameters:
    objects: |
      - objectName: "database-creds"
        objectType: "secretsmanager"
```

Here is my deployment yaml

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: application
spec:
  serviceAccountName: db-secret-access
  containers:
    - name: application
      image: busybox
      imagePullPolicy: IfNotPresent
      command:
        - "sleep"
        - "3600"
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-creds-csi
              key: password
      volumeMounts:
        - name: db-secret
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: db-secret
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "aws-secret-application"

```

I get the below error

```bash
Warning  Failed     5s (x3 over 7s)  kubelet            Error: secret "database-creds-csi" not found
```

However if I leave out the `env` section I can access the value if do this

```bash
kubectl exec -it application -- cat /mnt/secrets-store/database-creds; echo
{"password":"NEWPA$$WORD!!"}
```

Any help is appreciated. Thank you in advance.

**Comment by shapirov103** [comment]
Same issue here, trying to use secret sync feature:
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: argo-aws-secrets
spec:
  provider: aws
  secretObjects:
    - secretName: bootstrap-repo-secret-sync
      type: Opaque
      labels:
        "argocd.argoproj.io/secret-type": "repository"
      data:
        - objectName: github-ssp-ssh   
          key: sshPrivateKey
        - objectName: github-ssp-ssh
          key: url 
  parameters:
    objects: | 
      - objectName: "github-ssp-ssh"
        objectType: "secretsmanager"
```
The behavior is exactly as described in the issue: env reference fails, however volume is mounted successfully when kubernetes secret is not referenced. Secret is not created. 
On EKS version 1.19:
    AWS provider image: `public.ecr.aws/aws-secrets-manager/secrets-store-csi-driver-provider-aws:1.0.r1-10-g1942553-2021.06.04.00.07-linux-amd64`
    CSI Driver image: `k8s.gcr.io/csi-secrets-store/driver:v0.0.23`
