### ISSUE TITLE
secrets does not working on mysql-pods

### ISSUE THREAD

**Issue by bittu664** [aws/secrets-store-csi-driver-provider-aws#389]
**ERROR on Mysql-pods**

Here is my SecretProviderClass

```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-aws
spec:
  provider: aws
  parameters:
    region: ap-south-1
    objects: |
        - objectName: "mysql-prod-secrets"
          objectType: "secretsmanager"
          jmesPath:
          - path: "MYSQL_ROOT_PASSWORD"
            objectAlias: "MYSQL_ROOT_PASSWORD"
          - path: "MYSQL_USER"
            objectAlias: "MYSQL_USER"
          - path: "MYSQL_PASSWORD"
            objectAlias: "MYSQL_PASSWORD"


```

and this is my mysql deployment pods:-

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      serviceAccountName: new-csi-secret-driver-sa
      containers:
      - image: mysql:5.6
        name: mysql
        volumeMounts:
        - name: aws-secret
          mountPath: /mnt/secrets-store
          readOnly: true
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-aws
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: mydb
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: my-aws
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-aws
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
          name: mysql
      volumes:
      - name: aws-secret
        csi: 
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: my-aws

```

but after deploying this pods, i am gettitng this error:-  `Warning  Failed     4s (x3 over 19s)  kubelet            Error: secret "my-aws" not found`

also here you can check that **SecretProviderClass** is properlly installed my cluster
<img width="860" alt="Screenshot 2024-08-15 at 11 16 46 PM" src="https://github.com/user-attachments/assets/407346bc-a9fc-4318-a308-7d048d6958b2">

I want the solutions how i can inject my secrets into mysql pods.
