### ISSUE TITLE
Very very confuse hint: "Failed to fetch secret from all regions"   --- even secrets can be fetch.

### ISSUE THREAD

**Issue by johnzheng1975** [aws/secrets-store-csi-driver-provider-aws#401]
**Describe the bug**
I am trying csi on eks, fail the secrets from secret manager.
ALL is right, except I wrote one key wrong.
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: infra-demo-secrets-aws
  namespace: myns
spec:
  parameters:
    objects: |
      - objectName: arn:aws:secretsmanager:us-west-2:xxxxx
        objectAlias: dev-ai-infra
        jmesPath:
        - path: DB_AI_HIVE_URL  **# should be db_ai_hive_url**
          objectAlias: DB_AI_HIVE_URL
```

The error message showed when I describe pod
```
Warning  FailedMount  3m39s (x710 over 23h)  kubelet  MountVolume.SetUp failed for volume "secrets-store-test" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod xxx-dev/sklearn-harbor-container2-predictor-67b49f889d-rvqmb, err: rpc error: code = Unknown desc = Failed to fetch secret from all regions: arn:aws:secretsmanager:us-west-2:xxx:secret:dev-ai-infra-pmUT8Z
```

It make me thinking whether I give rights to this secrets or not.
Since cross cluster rights assign is very complex, **I cost almost one day** to debug -- whether I give enough rights to role, service account...., although root reason is just one secret key name is wrong. -- secrets can be fetch/list/view!

So, this error message is very very confuse, it should say, secrets can be get, but key DB_AI_HIVE_URL  does not exists!

**To Reproduce**

Do you also notice this bug when using a different secrets store provider (Vault/Azure/GCP...)? **Yes/No**

If yes, the issue is likely with the k8s Secrets Store CSI driver, not the AWS provider. Open an issue in [that repo](https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues).

**Expected behavior**

**Environment:**
OS, Go version, etc.

**Additional context**

I really think this should be improve, since configure rights is complex here!
You should provide useful info to user. Thanks.
