### ISSUE TITLE
secretObjects not working as expected

### ISSUE THREAD

**Issue by loshz** [aws/secrets-store-csi-driver-provider-aws#42]
Firstly, apologies if this is a misconfiguration on my end and not a bug.

I have the following Secrets Manager object:
```json
{
  "username": "admin",
  "password": "abc123",
}
```

And the following `SecretProviderClass`:
```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: database-secrets
spec:
  provider: aws   
  secretObjects:
  - secretName: db-creds
    type: Opaque
    data:
    - objectName: database-secrets
      key: username
    - objectName: database-secrets
      key: password
  parameters:
    objects: |
        - objectName: "database-secrets"
          objectType: "secretsmanager"
          jmesPath:
              - Path: "username"
                ObjectAlias: "username"
              - Path: "password"
                ObjectAlias: "password" 
```

This does create a secret with the correct fields, but the data inside them is always the full JSON object, and not the individual value (secret decoded for readability):
```yaml
apiVersion: v1
data:
  password: {"username":"admin","password":"abc123"}
  username: {"username":"admin","password":"abc123"}
kind: Secret
metadata:
  name: db-creds
type: Opaque
```

I expected:
```yaml
apiVersion: v1
data:
  password: "abc123"
  username: "admin"
kind: Secret
metadata:
  name: db-creds
type: Opaque
```

Versions:
- k8s: `1.21`
- secrets-store-csi-driver-provider-aws: `1.0.r2-2021.08.13.20.34-linux-amd64`
- secrets-store-csi-driver: `v0.2.0`

**Comment by cryptk** [comment]
@fert-f you are almost there.  Try something like this

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: csi-poc-aws-secrets
  namespace: kube-public
spec:
  secretObjects:                                
  - secretName: csi-poc
    type: Opaque
    labels:                                   
      provider: "csi-driver"
    data: 
    - objectName: csi-poc-username
      key: username
    - objectName: csi-poc-password
      key: password
  provider: aws
  parameters:
    objects: |
        - objectName: "/secrets/xxx/csi-poc"
          objectType: "secretsmanager"
          objectVersionLabel: "AWSCURRENT"
          objectAlias: csi-poc
          jmesPath:
          - path: "username"
            objectAlias: "csi-poc-username"
          - path: "password"
            objectAlias: "csi-poc-password"
```

Notice that rather than defining the secret twice, the secret is only defined a single time, just with two data items in it.

**Comment by oyamin** [comment]
I am almost there, but now I have separate file with correct credentials, but when I call my code, the env variables still have the full Json object:
`apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secret-application
spec:
  provider: aws
  secretObjects:
    - secretName: csi-secrets
      type: Opaque
      labels:                                   
        provider: "csi-driver"
      data:
        - objectName: postgresql_database
          key: main_database
        - objectName: postgresql_host
          key: main_host
        - objectName: postgresql_user
          key: main_username
        - objectName: postgresql_password
          key: main_password
  parameters:
    objects: |
      - objectName: "rds-secrets"
        objectType: "secretsmanager"
        objectAlias: csi-secrets
        jmesPath: 
          - path: "main_database"
            objectAlias: "postgresql_database"
          - path: "main_host"
            objectAlias: "postgresql_host"
          - path: "main_username"
            objectAlias: "postgresql_user"
          - path: "main_password"
            objectAlias: "postgresql_password"`
            
Which generates the files with correct values from each key:
`# ls -ltr /mnt/secrets-store/
total 20
-rw-r--r-- 1 root root   8 Aug 31 21:16 postgresql_user  # has the value of postgresql_user key
-rw-r--r-- 1 root root  20 Aug 31 21:16 postgresql_password  # has the value of postgresql_password key
-rw-r--r-- 1 root root  48 Aug 31 21:16 postgresql_host  # has the value of postgresql_host key
-rw-r--r-- 1 root root   7 Aug 31 21:16 postgresql_database  # has the value of postgresql_database key
-rw-r--r-- 1 root root 156 Aug 31 21:16 csi-secrets  # contains full JSON object with all the key/values ` 

When I call them in my Deploy, i still get each env variable that contains the full json:
`postgresql_host={"main_database":"value","main_host":"value","main_password":"value","main_username":"value"}
postgresql_database={"main_database":"value","main_host":"value","main_password":"value","main_username":"value"}
postgresql_user={"main_database":"value","main_host":"value","main_password":"value","main_username":"value"}`

deployment code:

`
      volumes:
        - name: api-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secret-application"
      containers:
        - name: api
          image: "{{ .Values.images.api.image.repository }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: api-secret
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
            - name: postgresql_database
              valueFrom:
                secretKeyRef:
                  name: postgresql_database
                  key: main_database
            - name: postgresql_host
              valueFrom:
                secretKeyRef:
                  name: postgresql_host
                  key: main_host
            - name: postgresql_user
              valueFrom:
                secretKeyRef:
                  name: ngs-rds-secrets
                  key: main_username
            - name: postgresql_password
              valueFrom:
                secretKeyRef:
                  name: ngs-rds-secrets
                  key: main_password
`

Not sure what else do try... or how to call those values from each file in the env

**Comment by fert-f** [comment]
@oyamin, I think you env should reference secret created by SecretProviderClass. Not sure where **ngs-rds-secrets** came from:
```
          env:
            - name: postgresql_database
              valueFrom:
                secretKeyRef:
                  name: csi-secrets
                  key: main_database
            - name: postgresql_host
              valueFrom:
                secretKeyRef:
                  name: csi-secrets
                  key: main_host
            - name: postgresql_user
              valueFrom:
                secretKeyRef:
                  name: csi-secrets
                  key: main_username
            - name: postgresql_password
              valueFrom:
                secretKeyRef:
                  name: csi-secrets
                  key: main_password
```
