### ISSUE TITLE
Allow multiple objects

### ISSUE THREAD

**Issue by rubensa** [aws/secrets-store-csi-driver-provider-aws#436]
**Describe the bug**
We are trying to create two **Kubernetes** secrets from two secrets in **Secrets Manager**.  Looks like as soon as there are two **Secrets Manager** secrets defined in `spec.parameters.objects`, the **Kubernetes** secrets are not created.

**To Reproduce**

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: test-secrets-store
spec:
  provider: aws
  parameters:
    # Secrets to be mounted
    objects: |
      - objectName: "test/secrets/one"
        objectAlias: "test-secretes-one"
        objectType: "secretsmanager"
        jmesPath:
          - path: "secret_one"
            objectAlias: "secret_one"
      - objectName: "test/secrets/two"
        objectAlias: "test-secretes-two"
        objectType: "secretsmanager"
        jmesPath:
          - path: "secret_two"
            objectAlias: "secret_two"
  # Create k8s secret. It requires volume mount first in the pod and then sync.
  secretObjects:
    - secretName: "test-secrets-one"
      type: Opaque
      data:
        - objectName: "secret_one"
          key: "SECRET_ONE"
    - secretName: "test-secrets-two"
      type: Opaque
      data:
        - objectName: "secret_two"
          key: "SECRET_TWO"
```

And this an extract from the deployment mounting the `test-secrets-store`.
```yaml
apiVersion: apps/v1
kind: Deployment
...
spec:
  template:
    spec:
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "test-secrets-store"
      containers:
        - name: "test-container"
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
```

If I remove `test/secrets/two`, keeping only one **Secrets Manager** secret in `spec.parameters.objects` everything works as expected.

Do you also notice this bug when using a different secrets store provider (Vault/Azure/GCP...)? **Not tested with other providers**

**Expected behavior**

Both **Secrets Manager** secrets are mounted and they can be used to create **Kubernetes** secrets. 

**Environment:**

AWS EKS (Kubernetes 1.30)
