### ISSUE TITLE
jmespath parsing breaks on hyphens

### ISSUE THREAD

**Issue by mf-lit** [aws/secrets-store-csi-driver-provider-aws#66]
Given the following payload in a SecretsManager Secret:
```
{
  "api-key": "xxxxx",
  "app-key": "yyyyy"
}
```
And the following secretproviderclass config:
```
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "thissecret"
        objectType: secretsmanager
        jmesPath:
          - path: "api-key"
            objectAlias: "api-key"
          - path: "app-key"
            objectAlias: "app-key"
```
Pods fail to start with the following event message:
```
 Invalid JMES Path: api-key
```

Removing the hyphen from the keys "solves" the problem.

(provider version: 1.0.r2-2021.08.13.20.34-linux-amd64)
