### ISSUE TITLE
While creating `SecretProviderClass` with secret object that receive parameter from parameter store in AWS I get `Failed to load SecretProviderClass: error unmarshaling JSON`

### ISSUE THREAD

**Issue by Ferat-Imrak** [aws/secrets-store-csi-driver-provider-aws#77]
I created `SecretProviderClass` with secret objects to get parameters from the parameter store and mount them into deployment and use them as env variables. When I run kubectl apply -f secret.yaml file it creates `SecretProviderClass` but not secrets and I get this error:
```
E0413 16:20:12.505048       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod production/new-app-7fcb466856-z4d7m, err: rpc error: code = Unknown desc = Failed to load SecretProviderClass: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go value of type []*provider.SecretDescriptor
```

Here is my secret.yaml file:
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: production
spec:
  provider: aws
  secretObjects:
  - secretName: api-token
    type: Opaque
    data: 
    - objectName: my-secret
      key: SECRET_01
    - objectName: standard-string
      key: SECRET_02
  parameters:
    objects: |
      array:
        - |
          objectName: my-secret
          objectType: ssmparameter
          objectAlias: my-secret
        - |
          objectName: standard-string
          objectType: ssmparameter
          objectAlias: standard-string
```

I expect to create `/mnt/secrets-store/my-secret` and `/mnt/secrets-store/standard-string` in the pod and use these variables as env variables.

First, I tried to mount one object to the deployment which `my-secret`  and it worked but then I tried two objects to mount the same deployment, and I got the error I posted above.

Secrets Store CSI Driver version: (use the image tag): storage.k8s.io/v1
Kubernetes version: (use kubectl version): Client version: v1.23 Server version: `1.21'

**Comment by Ferat-Imrak** [comment]
Solved:

Here is how secret.yaml file should be:
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: production
spec:
  provider: aws
  secretObjects:
  - secretName: api-token
    type: Opaque
    data: 
    - objectName: my-secret
      key: SECRET_01
    - objectName: standard-string
      key: SECRET_02
  parameters:
    objects: |
        - objectName: my-secret
          objectType: ssmparameter
        - objectName: standard-string
          objectType: ssmparameter
```
