### ISSUE TITLE
Can't reference AWSCURRENT and AWSPREVIOUS in the same secretproviderclass

### ISSUE THREAD

**Issue by sergei-riazanov-privitar** [aws/secrets-store-csi-driver-provider-aws#95]
The configuration I want to use:
```
spec:
  parameters:
    objects: |
      ---
      - objectAlias: "encryption-key"
        objectVersionLabel: "AWSCURRENT"
        objectName: "arn:aws:secretsmanager:XXX"
        objectType: "secretsmanager"
      - objectAlias: "previous-encryption-key"
        objectVersionLabel: "AWSPREVIOUS"
        objectName: "arn:aws:secretsmanager:XXX"
        objectType: "secretsmanager"
  provider: aws
  secretObjects:
  - data:
    - key: encryption-key
      objectName: encryption-key
    - key: previous-encryption-key
      objectName: previous-encryption-key
    secretName: YYY
    type: Opaque
```

As result I get this on mounting the volume:
"Warning  FailedMount             71s (x9 over 3m19s)  kubelet                     MountVolume.SetUp failed for volume "YYY" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod ..., err: rpc error: code = Unknown desc = Name already in use for objectName: arn:aws:secretsmanager:XXX"
